# Generated by Django 4.2.2 on 2023-09-14 14:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('examinator', models.CharField(max_length=50, null=True)),
                ('course_name', models.CharField(max_length=120)),
                ('hp', models.CharField(default=1, max_length=5)),
                ('level', models.CharField(max_length=20)),
                ('campus', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainField',
            fields=[
                ('field_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_name', models.CharField(max_length=120)),
                ('profile_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('profiles', models.ManyToManyField(to='planning.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('block', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('scheduler_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.course')),
                ('linked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.scheduler')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulersProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vof', models.CharField(max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.profile')),
                ('scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.scheduler')),
            ],
        ),
        migrations.AddField(
            model_name='scheduler',
            name='profiles',
            field=models.ManyToManyField(through='planning.SchedulersProfiles', to='planning.profile'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.program'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.schedule'),
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hp', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('grading', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=10)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='main_fields',
            field=models.ManyToManyField(to='planning.mainfield'),
        ),
    ]
