# Generated by Django 4.2.2 on 2023-06-27 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('examinator', models.CharField(blank=True, max_length=50, null=True)),
                ('course_name', models.CharField(max_length=120)),
                ('hp', models.CharField(max_length=5)),
                ('level', models.CharField(max_length=20)),
                ('vof', models.CharField(max_length=5)),
                ('campus', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('profile_code', models.CharField(max_length=10)),
                ('profile_courses', models.ManyToManyField(to='planning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('program_courses', models.ManyToManyField(to='planning.course')),
                ('program_profiles', models.ManyToManyField(to='planning.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('period', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('block', models.CharField(max_length=10)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.course')),
                ('program_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.program')),
            ],
        ),
        migrations.CreateModel(
            name='MainField',
            fields=[
                ('field_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.course')),
            ],
        ),
    ]
